### ISSUE TITLE
harbor-repo.vmware.com not accessible

### ISSUE THREAD

**Issue by TimTinneveld** [vmware/cluster-api-provider-cloud-director#216]
### Describe the bug

I saw that the registry was changed in main, changed to: harbor-repo.vmware.com.

for me this is not an address that is accessible. Now my question is do I have to submit these images myself or will this be made public?

I'm sorry I'm still a bit new to this, but the tag says it's in beta, this means the main version is still under testing and not ready for production? because this is also the transition from alpha to beta in the kubernetes api version. This is giving me a bit of confusion. Upgrading is then possible with clusterctl moving i guess? Sorry for the extra questions.

Thanks in advance!

### Reproduction steps

```bash
1. executing clusterctl init with main version, pods give image pull error. 
2. Also the link is not reachable.
```

### Expected behavior

Link is not available for harbor-repo.vmware.com/vcloud/cluster-api-provider-cloud-director:main-branch.

**Comment by TimTinneveld** [comment]
Hi VXAV,

Thank you for the response. This is really helping me in our journy to capvcd.

I actually still have few short questions. 

1. is it possible then for the management cluster to manage its own nodes?
2. If i move the objects. the objects loses it status. Is there a way to preserve this information or being recreated.

I have tried to use the mv once, but it has resulted into an un working cluster. 

For me it is actually still very vague how management will eventually be upgraded and what to do in case of failure of the management cluster. Upgrading nodes of management cluster. I can't find any documentation about this.

I also know that you can back-up with clusterctl. But if you are missing the status how are gonna recover this?

**Comment by vxav** [comment]
> is it possible then for the management cluster to manage its own nodes?

Yes, once you do `clusterctl move`, the cluster starts "managing itself" as the CRs describing it are now self-hosted.

> If i move the objects. the objects loses it status. Is there a way to preserve this information or being recreated.

Indeed, the issue is because the RDE ID is stored in `status` which, like you said, isn't copied over during clusterctl move which is [per design](https://github.com/kubernetes-sigs/cluster-api/issues/2370#issuecomment-588219695). In which case the VCDCluster object would get a new ID in the destination so it would try to create a new LB based on that ID with an IP that was already applied to the previous one. The workaround in a fairly recent build is to set [skipRDE](https://github.com/vmware/cluster-api-provider-cloud-director/blob/main/config/crd/bases/infrastructure.cluster.x-k8s.io_vcdclusters.yaml#L206) to `true` (I'm guessing you haven't registered the API schema). The maintainers are looking at a better way to solve that, probably by adding RdeID to the `spec` section but the decision is mostly best-practices driven.

It was [raised ](https://kubernetes.slack.com/archives/C8TSNPY4T/p1661451980545679)recently as to whether it is good practice to put more info in the `spec` section or not. This is where it gets tricky to align providers implementations and needs with CAPI recommendations. 

> For me it is actually still very vague how management will eventually be upgraded and what to do in case of failure of the management cluster. Upgrading nodes of management cluster. I can't find any documentation about this.

A management cluster is similar to a workload cluster, except it runs capi stuff. There's a short doc for [capi](https://cluster-api.sigs.k8s.io/tasks/upgrading-clusters.html) and [capvcd](https://github.com/vmware/cluster-api-provider-cloud-director/blob/main/docs/WORKLOAD_CLUSTER.md#upgrade-a-workload-cluster). Also I suggest you have a look at managing your clusters using FluxCD as it will simplify configuration management and versioning.

**Comment by TimTinneveld** [comment]
Thank you again vxav for the information,

Last time I tried to move it, I saw that it was missing a few objects and all the nodes had no status anymore. Also all the objects in the (vcdclusters.infrastructure) wasn't there anymore. When i tried to add the missing objects it just turned off all the vm's in management cluster, for it to be completely unrecoverable. After all of this i am bit careful of trying it again.

I will set up a test environment this week and try it again to move the objects from the bootstrapcluster to management.

I have not used any gitops tools yet. My plan was to eventually move to ArgoCD. But i don't know if FluxCD would be a better option for CAPVCD or that it is just a preference.

**Comment by vxav** [comment]
> Also all the objects in the (vcdclusters.infrastructure) wasn't there anymore

I'm guessing you were still looking in the bootstrap cluster, it is normal since the objects were moved to the destination cluster. You pretty much have 2 options at this stage:

1.  Use whatever version you are using and delete the "old" virtual service when the controller tries to create a new LB after running clusterctl move.
2. Build a new image with main and use skipRDE.

**Comment by TimTinneveld** [comment]
No those the objects were still in bootstrapcluster and not in the cluster where i moved it to weirdly enough. clustercrtl move skipped the (vcdclusters.infrastructure) part, Maybe this was a one time thing.  But i am gonna try again this week and share the results. I also put the management cluster in a specified namespace, I hope that is also not gonna make any difference.

for your information at the moment i am still using version: 0.5.1.

**Comment by TimTinneveld** [comment]
Hi vxav,

Sorry i couldn't test it any earlier. I have successfully created a test: boostrapcluster and a management cluster. When every i do the clusterctl move, these cluster objects are transferred:
- clusters.cluster.x-k8s.io
- machines.cluster.x-k8s.io
- machinesets.cluster.x-k8s.io
- machinedeployments.cluster.x-k8s.io

Only the vcd.infrastructure objects are not send over and still exists on the bootstrapcluster:
- vcdclusters.infrastructure.cluster.x-k8s.io
- vcdmachines.infrastructure.cluster.x-k8s.io
- vcdmachinetemplates.infrastructure.cluster.x-k8s.io

Do i create these vcd.infrastructure object manually? because if I "kubectl  get vcdclusters.infrastructure.cluster.x-k8s.io 
 -o yaml > ..." and i create it on the other cluster lacking the vcd.infrastructure parts. It turns off all the VM's and the management cluster becomes completely unrecoverable.

**Comment by vxav** [comment]
No you don't create them manually. You're probably missing labels on your CRs which means `clusterctl move` ignores them. These should be automatically added to the CRDs when generating the manifests with kustomize when installing the controller (if that's how you did it.)
```
    clusterctl.cluster.x-k8s.io: ""
    clusterctl.cluster.x-k8s.io/move: ""
```

**Comment by TimTinneveld** [comment]
I do see the infrastructure objects in the CRDs. Only when i check the CRs it is missing the label: clusterctl.cluster.x-k8s.io/move: "". Can i simple add this label to the CRs to make it work? 

I can see that this label is present on the crs ' clusterctl.cluster.x-k8s.io: "" '

I also just tried to add it, but it doesn't seem to make any difference, probably missing some extra steps i guess.

The machines are still stuck in the new management cluster:
capi-test-mgmt-cluster-control-plane-c2c46       test-mgmt-cluster   11m   vmware-cloud-director://urn:vcloud:vm:7c353a91-f533-489b-a144-7d6fd46cf14f   Provisioned v1.21.11+vmware.1

while the infrastructure objects are still in the bootstrap cluster. 

I really want to make it work. But i seem to be lacking the knowledge on how to do this.

**Comment by vxav** [comment]
Yeah you can try adding `clusterctl.cluster.x-k8s.io/move: ""` to the CustomResources but you should add it also to the `CustomResourceDefinitions` so further objects will get it automatically.
It's the same if you have to move a secret for the credentials for instance, you'll need this label.

**Comment by TimTinneveld** [comment]
Hi Vxav,

That was the solution to the problem!

I have added both labels to the three CRD. I saw that the other objects of CRD did contain: "clusterctl.cluster.x-k8s.io: """
Why the cluster was lacking this label on the infrastructure CRD, I don't know. I am very happy that this easy fix did the trick. 

After that i let the system recreate the load balancer setting on the same IP (like you said before), everything seem to be working fine now.

Thanks for your help.

**Comment by vxav** [comment]
Glad it helped.

Depends how you created your manifests and set up CAPVCD. Because it's in the [kustomization](https://github.com/vmware/cluster-api-provider-cloud-director/blob/main/config/crd/kustomization.yaml) and [template](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f4a210aa4850c1a487fc3067a8da064db569615e/templates/infrastructure-components.yaml#L19).

**Comment by TimTinneveld** [comment]
The newest version it is. For now i am still at 0.5.1, back then i think it wasn't in there yet. 

For now stil waiting for a good moment to move over to version 1.0.

**Comment by OlofKalufs** [comment]
According to this page: https://docs.vmware.com/en/VMware-Cloud-Director-Container-Service-Extension/4.0/rn/vmware-cloud-director-container-service-extension-40-release-notes/index.html
CAPVCD 1.0.0 should be released alongside CSE 4, which was released last week. Do you have an ETA for when the 1.0.0-version will be accessible from a public registry?
